import React, { useState } from "react";
import "./styles/main.css";
import Score from "./components/Score";

const scores = [
  {
    startTime: "2020-09-08T19:15Z",
    shortName: "MIN @ STL",
    status: {
      inning: 1,
      state: "in",
      detail: "Top 1st",
      shortDetail: "Top 1st",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Twins",
        alternateColor: "f1f2f3",
        color: "012756",
        displayName: "Minnesota Twins",
        name: "Twins",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/min.png",
        location: "Minnesota",
        abbreviation: "MIN",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Cardinals",
        alternateColor: "ffffff",
        color: "b80220",
        displayName: "St. Louis Cardinals",
        name: "Cardinals",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/stl.png",
        location: "St. Louis",
        abbreviation: "STL",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T20:05Z",
    shortName: "BOS @ PHI",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 4:05 PM EDT",
      shortDetail: "9/8 - 4:05 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Red Sox",
        alternateColor: "0d2b56",
        color: "00224b",
        displayName: "Boston Red Sox",
        name: "Red Sox",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/bos.png",
        location: "Boston",
        abbreviation: "BOS",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Phillies",
        alternateColor: "284898",
        color: "be0011",
        displayName: "Philadelphia Phillies",
        name: "Phillies",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/phi.png",
        location: "Philadelphia",
        abbreviation: "PHI",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T22:05Z",
    shortName: "TB @ WSH",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 6:05 PM EDT",
      shortDetail: "9/8 - 6:05 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Rays",
        alternateColor: "8fbce6",
        color: "002454",
        displayName: "Tampa Bay Rays",
        name: "Rays",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/tb.png",
        location: "Tampa Bay",
        abbreviation: "TB",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Nationals",
        alternateColor: "f1f2f3",
        color: "0a295d",
        displayName: "Washington Nationals",
        name: "Nationals",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/wsh.png",
        location: "Washington",
        abbreviation: "WSH",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T22:10Z",
    shortName: "KC @ CLE",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 6:10 PM EDT",
      shortDetail: "9/8 - 6:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Royals",
        alternateColor: "7ab2dd",
        color: "003b72",
        displayName: "Kansas City Royals",
        name: "Royals",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/kc.png",
        location: "Kansas City",
        abbreviation: "KC",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Indians",
        alternateColor: "002b5c",
        color: "00264e",
        displayName: "Cleveland Indians",
        name: "Indians",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/cle.png",
        location: "Cleveland",
        abbreviation: "CLE",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T22:10Z",
    shortName: "OAK @ HOU",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 6:10 PM EDT",
      shortDetail: "9/8 - 6:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Athletics",
        alternateColor: "efb21e",
        color: "014326",
        displayName: "Oakland Athletics",
        name: "Athletics",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/oak.png",
        location: "Oakland",
        abbreviation: "OAK",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Astros",
        alternateColor: "eb6e1f",
        color: "000000",
        displayName: "Houston Astros",
        name: "Astros",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/hou.png",
        location: "Houston",
        abbreviation: "HOU",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T22:15Z",
    shortName: "MIN @ STL",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 6:15 PM EDT",
      shortDetail: "9/8 - 6:15 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Twins",
        alternateColor: "f1f2f3",
        color: "012756",
        displayName: "Minnesota Twins",
        name: "Twins",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/min.png",
        location: "Minnesota",
        abbreviation: "MIN",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Cardinals",
        alternateColor: "ffffff",
        color: "b80220",
        displayName: "St. Louis Cardinals",
        name: "Cardinals",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/stl.png",
        location: "St. Louis",
        abbreviation: "STL",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T22:37Z",
    shortName: "NYY @ TOR",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 6:37 PM EDT",
      shortDetail: "9/8 - 6:37 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Yankees",
        alternateColor: "c4ced4",
        color: "011739",
        displayName: "New York Yankees",
        name: "Yankees",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/nyy.png",
        location: "New York",
        abbreviation: "NYY",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Blue Jays",
        alternateColor: "1d2d5c",
        color: "0069ac",
        displayName: "Toronto Blue Jays",
        name: "Blue Jays",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/tor.png",
        location: "Toronto",
        abbreviation: "TOR",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T23:05Z",
    shortName: "CHW @ PIT",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 7:05 PM EDT",
      shortDetail: "9/8 - 7:05 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "White Sox",
        alternateColor: "c4ced4",
        color: "1b1516",
        displayName: "Chicago White Sox",
        name: "White Sox",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/chw.png",
        location: "Chicago",
        abbreviation: "CHW",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Pirates",
        alternateColor: "000000",
        color: "111111",
        displayName: "Pittsburgh Pirates",
        name: "Pirates",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/pit.png",
        location: "Pittsburgh",
        abbreviation: "PIT",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T23:05Z",
    shortName: "BOS @ PHI",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 7:05 PM EDT",
      shortDetail: "9/8 - 7:05 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Red Sox",
        alternateColor: "0d2b56",
        color: "00224b",
        displayName: "Boston Red Sox",
        name: "Red Sox",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/bos.png",
        location: "Boston",
        abbreviation: "BOS",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Phillies",
        alternateColor: "284898",
        color: "be0011",
        displayName: "Philadelphia Phillies",
        name: "Phillies",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/phi.png",
        location: "Philadelphia",
        abbreviation: "PHI",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T23:10Z",
    shortName: "MIA @ ATL",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 7:10 PM EDT",
      shortDetail: "9/8 - 7:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Marlins",
        alternateColor: "0077c8",
        color: "0081c7",
        displayName: "Miami Marlins",
        name: "Marlins",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/mia.png",
        location: "Miami",
        abbreviation: "MIA",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Braves",
        alternateColor: "f1f2f3",
        color: "002248",
        displayName: "Atlanta Braves",
        name: "Braves",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/atl.png",
        location: "Atlanta",
        abbreviation: "ATL",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T23:10Z",
    shortName: "MIL @ DET",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 7:10 PM EDT",
      shortDetail: "9/8 - 7:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Brewers",
        alternateColor: "f1f2f3",
        color: "050C33",
        displayName: "Milwaukee Brewers",
        name: "Brewers",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/mil.png",
        location: "Milwaukee",
        abbreviation: "MIL",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Tigers",
        alternateColor: "ff6600",
        color: "002d5c",
        displayName: "Detroit Tigers",
        name: "Tigers",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/det.png",
        location: "Detroit",
        abbreviation: "DET",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-08T23:10Z",
    shortName: "BAL @ NYM",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 7:10 PM EDT",
      shortDetail: "9/8 - 7:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Orioles",
        alternateColor: "000000",
        color: "201b1b",
        displayName: "Baltimore Orioles",
        name: "Orioles",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/bal.png",
        location: "Baltimore",
        abbreviation: "BAL",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Mets",
        alternateColor: "00407b",
        color: "00407b",
        displayName: "New York Mets",
        name: "Mets",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/nym.png",
        location: "New York",
        abbreviation: "NYM",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T00:05Z",
    shortName: "LAA @ TEX",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 8:05 PM EDT",
      shortDetail: "9/8 - 8:05 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Angels",
        alternateColor: "862633",
        color: "a50017",
        displayName: "Los Angeles Angels",
        name: "Angels",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/laa.png",
        location: "Los Angeles",
        abbreviation: "LAA",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Rangers",
        alternateColor: "c0111f",
        color: "003879",
        displayName: "Texas Rangers",
        name: "Rangers",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/tex.png",
        location: "Texas",
        abbreviation: "TEX",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T00:15Z",
    shortName: "CIN @ CHC",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 8:15 PM EDT",
      shortDetail: "9/8 - 8:15 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Reds",
        alternateColor: "ffffff",
        color: "c41422",
        displayName: "Cincinnati Reds",
        name: "Reds",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/cin.png",
        location: "Cincinnati",
        abbreviation: "CIN",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Cubs",
        alternateColor: "00417d",
        color: "00417d",
        displayName: "Chicago Cubs",
        name: "Cubs",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/chc.png",
        location: "Chicago",
        abbreviation: "CHC",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T01:10Z",
    shortName: "HOU @ OAK",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 9:10 PM EDT",
      shortDetail: "9/8 - 9:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Astros",
        alternateColor: "eb6e1f",
        color: "000000",
        displayName: "Houston Astros",
        name: "Astros",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/hou.png",
        location: "Houston",
        abbreviation: "HOU",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Athletics",
        alternateColor: "efb21e",
        color: "014326",
        displayName: "Oakland Athletics",
        name: "Athletics",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/oak.png",
        location: "Oakland",
        abbreviation: "OAK",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T01:10Z",
    shortName: "COL @ SD",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 9:10 PM EDT",
      shortDetail: "9/8 - 9:10 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Rockies",
        alternateColor: "220d48",
        color: "220d48",
        displayName: "Colorado Rockies",
        name: "Rockies",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/col.png",
        location: "Colorado",
        abbreviation: "COL",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Padres",
        alternateColor: "ffc425",
        color: "2f241d",
        displayName: "San Diego Padres",
        name: "Padres",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/sd.png",
        location: "San Diego",
        abbreviation: "SD",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T01:40Z",
    shortName: "LAD @ ARI",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 9:40 PM EDT",
      shortDetail: "9/8 - 9:40 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Dodgers",
        alternateColor: "a2aaad",
        color: "00337f",
        displayName: "Los Angeles Dodgers",
        name: "Dodgers",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/lad.png",
        location: "Los Angeles",
        abbreviation: "LAD",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Diamondbacks",
        alternateColor: "000000",
        color: "a40013",
        displayName: "Arizona Diamondbacks",
        name: "Diamondbacks",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/ari.png",
        location: "Arizona",
        abbreviation: "ARI",
        isActive: true,
        score: "0",
      },
    },
  },
  {
    startTime: "2020-09-09T01:45Z",
    shortName: "SEA @ SF",
    status: {
      inning: 1,
      state: "pre",
      detail: "Tue, September 8th at 9:45 PM EDT",
      shortDetail: "9/8 - 9:45 PM EDT",
      completed: false,
    },
    teams: {
      awayTeam: {
        shortDisplayName: "Mariners",
        alternateColor: "0c2c56",
        color: "012a5b",
        displayName: "Seattle Mariners",
        name: "Mariners",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/sea.png",
        location: "Seattle",
        abbreviation: "SEA",
        isActive: true,
        score: "0",
      },
      homeTeam: {
        shortDisplayName: "Giants",
        alternateColor: "000000",
        color: "161415",
        displayName: "San Francisco Giants",
        name: "Giants",
        logo: "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/sf.png",
        location: "San Francisco",
        abbreviation: "SF",
        isActive: true,
        score: "0",
      },
    },
  },
];

function App() {
  // const [scores, setScores] = useState([])
  // const getBaseballScores = async () => {
  //   const res = await fetch("https://score-board-api.herokuapp.com/api/v1/sports/mlb/events");
  //   const data = await res.json();
  // }
  return (
    <div className="h-screen w-full bg-black text-white flex">
      <div className="w-32 px-6 border-r border-white flex flex-col items-center justify-center">
        <div className="my-4 cursor-pointer">MLB</div>
        <div className="my-4 cursor-pointer">NFL</div>
        <div className="my-4 cursor-pointer">NBA</div>
      </div>
      <div className="flex w-full flex-wrap py-12 h-screen overflow-x-auto">
        {scores.map((s) => (
          <Score key={s.shortName + s.startTime} game={s} />
        ))}
      </div>
    </div>
  );
}

export default App;
